// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setttings.sql

package sqlc

import (
	"context"
)

const deleteUserSetting = `-- name: DeleteUserSetting :exec
DELETE FROM settings
WHERE key = ?
`

func (q *Queries) DeleteUserSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSetting, key)
	return err
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT
    id, key, value, created_at, updated_at
FROM
    settings
WHERE
    key = ?
LIMIT 1
`

func (q *Queries) GetUserSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getUserSetting, key)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSettings = `-- name: ListUserSettings :many
SELECT
    id, key, value, created_at, updated_at
FROM
    settings
ORDER BY key
`

func (q *Queries) ListUserSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listUserSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSetting = `-- name: SetUserSetting :exec
INSERT INTO settings (key, value, created_at, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = CURRENT_TIMESTAMP
`

type SetUserSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetUserSetting(ctx context.Context, arg SetUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, setUserSetting, arg.Key, arg.Value)
	return err
}
